from typing import List, Dict
from pathlib import Path
import os


class MarkdownGenerator:
    """
    Generates numbered markdown lists of movies with confidence scores.
    """
    
    def __init__(self, output_dir: str = "output"):
        """
        Initialize markdown generator.
        
        Args:
            output_dir: Directory to save markdown files
        """
        self.output_dir = output_dir
        Path(output_dir).mkdir(parents=True, exist_ok=True)
    
    def generate_movie_list(self, titles: List[Dict], oleada_number: int) -> str:
        """
        Generate numbered markdown list of movies.
        
        Args:
            titles: List of validated title dictionaries
            oleada_number: Oleada edition number
            
        Returns:
            Markdown content as string
        """
        markdown_lines = [
            f"# Oleada {oleada_number:02d} - Movie List\n",
            f"**Total Movies:** {len(titles)}\n",
            "---\n"
        ]
        
        for idx, title_data in enumerate(titles, start=1):
            confidence_pct = title_data['confidence'] * 100
            title = title_data['final_title']
            timestamp = title_data.get('timestamp', 0)
            
            timestamp_str = self._format_timestamp(timestamp)
            
            line = f"{idx}. **{title}** (Confidence: {confidence_pct:.0f}%, Time: {timestamp_str})"
            
            if title_data.get('user_selected'):
                ocr = title_data.get('ocr_title', 'N/A')
                audio = title_data.get('audio_title', 'N/A')
                line += f"\n   - 👤 User selected \"{title}\" from OCR: \"{ocr}\" / Audio: \"{audio}\""
            
            markdown_lines.append(line)
        
        markdown_lines.append("\n---\n")
        markdown_lines.append("*Generated by Movie List Maker*\n")
        
        return '\n'.join(markdown_lines)
    
    def _format_timestamp(self, seconds: float) -> str:
        """
        Format timestamp in MM:SS format.
        
        Args:
            seconds: Timestamp in seconds
            
        Returns:
            Formatted timestamp string
        """
        minutes = int(seconds // 60)
        secs = int(seconds % 60)
        return f"{minutes:02d}:{secs:02d}"
    
    def save_markdown(self, content: str, filename: str) -> str:
        """
        Save markdown content to file.
        
        Args:
            content: Markdown content
            filename: Output filename (without extension)
            
        Returns:
            Path to saved file
        """
        if not filename.endswith('.md') and not filename.endswith('.qmd'):
            filename += '.qmd'
        
        filepath = os.path.join(self.output_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"✅ Markdown saved to: {filepath}")
        return filepath
    
    def generate_index_page(self, oleadas: List[int]) -> str:
        """
        Generate index page for Quarto website.
        
        Args:
            oleadas: List of oleada numbers
            
        Returns:
            Markdown content for index page
        """
        markdown_lines = [
            "# Movie List Collection\n",
            "Welcome to the Movie List Collection! Browse movies from different Oleadas.\n",
            "---\n",
            "## Available Oleadas\n"
        ]
        
        for oleada in sorted(oleadas):
            markdown_lines.append(f"- [Oleada {oleada:02d}](oleada-{oleada:02d}.qmd)")
        
        markdown_lines.append("\n---\n")
        markdown_lines.append("*Generated by Movie List Maker*\n")
        
        return '\n'.join(markdown_lines)
