import os
import yaml
from pathlib import Path
from typing import List, Dict


class QuartoGenerator:
    """
    Generates Quarto website configuration and structure.
    """
    
    def __init__(self, project_dir: str = "quarto_site"):
        """
        Initialize Quarto generator.
        
        Args:
            project_dir: Directory for Quarto project
        """
        self.project_dir = project_dir
        Path(project_dir).mkdir(parents=True, exist_ok=True)
    
    def generate_quarto_config(self, oleadas: List[int], project_title: str = "Movie List Collection") -> str:
        """
        Generate _quarto.yml configuration file.
        
        Args:
            oleadas: List of oleada numbers
            project_title: Title for the website
            
        Returns:
            Path to generated config file
        """
        navbar_items = [
            {
                'href': 'index.qmd',
                'text': 'Home'
            }
        ]
        
        for oleada in sorted(oleadas):
            navbar_items.append({
                'href': f'oleada-{oleada:02d}.qmd',
                'text': f'Oleada {oleada:02d}'
            })
        
        config = {
            'project': {
                'type': 'website',
                'output-dir': 'docs'
            },
            'website': {
                'title': project_title,
                'navbar': {
                    'left': [navbar_items[0]],
                    'right': navbar_items[1:]
                },
                'page-footer': {
                    'center': 'Generated by Movie List Maker'
                }
            },
            'format': {
                'html': {
                    'theme': 'cosmos',
                    'css': 'styles.css',
                    'toc': True,
                    'toc-depth': 2
                }
            }
        }
        
        config_path = os.path.join(self.project_dir, '_quarto.yml')
        
        with open(config_path, 'w', encoding='utf-8') as f:
            yaml.dump(config, f, default_flow_style=False, sort_keys=False)
        
        print(f"✅ Quarto config saved to: {config_path}")
        return config_path
    
    def create_styles_css(self) -> str:
        """
        Create custom CSS file for styling.
        
        Returns:
            Path to CSS file
        """
        css_content = """/* Custom styles for Movie List Collection */

body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
}

h1 {
    color: #2c3e50;
    border-bottom: 3px solid #3498db;
    padding-bottom: 10px;
}

h2 {
    color: #34495e;
    margin-top: 30px;
}

ol {
    line-height: 1.8;
}

ol li {
    margin-bottom: 10px;
}

.confidence-high {
    color: #27ae60;
}

.confidence-medium {
    color: #f39c12;
}

.confidence-low {
    color: #e74c3c;
}

hr {
    border: 0;
    height: 1px;
    background: #ecf0f1;
    margin: 30px 0;
}
"""
        
        css_path = os.path.join(self.project_dir, 'styles.css')
        
        with open(css_path, 'w', encoding='utf-8') as f:
            f.write(css_content)
        
        print(f"✅ CSS file saved to: {css_path}")
        return css_path
    
    def create_gitignore(self) -> str:
        """
        Create .gitignore for Quarto project.
        
        Returns:
            Path to .gitignore file
        """
        gitignore_content = """/.quarto/
/_site/
/.vscode/
*.pyc
__pycache__/
"""
        
        gitignore_path = os.path.join(self.project_dir, '.gitignore')
        
        with open(gitignore_path, 'w', encoding='utf-8') as f:
            f.write(gitignore_content)
        
        return gitignore_path
    
    def setup_github_pages(self) -> str:
        """
        Create .nojekyll file for GitHub Pages.
        
        Returns:
            Path to .nojekyll file
        """
        docs_dir = os.path.join(self.project_dir, 'docs')
        Path(docs_dir).mkdir(parents=True, exist_ok=True)
        
        nojekyll_path = os.path.join(docs_dir, '.nojekyll')
        
        with open(nojekyll_path, 'w') as f:
            f.write('')
        
        print(f"✅ GitHub Pages setup complete: {nojekyll_path}")
        return nojekyll_path
    
    def generate_readme(self) -> str:
        """
        Generate README for Quarto project.
        
        Returns:
            Path to README file
        """
        readme_content = """# Movie List Collection - Quarto Website

This Quarto website contains movie lists extracted from video recordings.

## Building the Site

To build the website locally:

```bash
quarto render
```

The site will be generated in the `docs/` directory.

## Publishing to GitHub Pages

1. Push the repository to GitHub
2. Go to repository Settings → Pages
3. Set source to "Deploy from a branch"
4. Select branch: `main` and folder: `/docs`
5. Save and wait for deployment

## Project Structure

- `_quarto.yml` - Quarto configuration
- `index.qmd` - Home page
- `oleada-*.qmd` - Individual movie list pages
- `styles.css` - Custom styling
- `docs/` - Generated website (for GitHub Pages)

## Theme

This site uses the **Cosmos** theme from Quarto.
"""
        
        readme_path = os.path.join(self.project_dir, 'README.md')
        
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(readme_content)
        
        print(f"✅ README saved to: {readme_path}")
        return readme_path
